platform :ios, '10.0'

target 'SubscriptionStateDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SwiftyStoreKit'
  pod 'SubscriptionState', :path => '..'

  target 'SubscriptionStateDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
